python train_reinforce.py --task_id sharded-livecodebench/2883
python train_reinforce.py --task_id sharded-livecodebench/2954
python train_reinforce.py --task_id sharded-HumanEval/59
python train_reinforce.py --task_id sharded-livecodebench/2888
python train_reinforce.py --task_id sharded-livecodebench/2756
python train_reinforce.py --task_id sharded-livecodebench/2847
python train_reinforce.py --task_id sharded-livecodebench/2791
python train_reinforce.py --task_id sharded-HumanEval/109
python train_reinforce.py --task_id sharded-livecodebench/2802
python train_reinforce.py --task_id sharded-HumanEval/99
python train_reinforce.py --task_id sharded-livecodebench/2844
python train_reinforce.py --task_id sharded-livecodebench/2816
python train_reinforce.py --task_id sharded-livecodebench/2792
python train_reinforce.py --task_id sharded-livecodebench/2828
python train_reinforce.py --task_id sharded-HumanEval/39
python train_reinforce.py --task_id sharded-livecodebench/2873
python train_reinforce.py --task_id sharded-livecodebench/2811
python train_reinforce.py --task_id sharded-HumanEval/17
python train_reinforce.py --task_id sharded-livecodebench/2877
python train_reinforce.py --task_id sharded-HumanEval/128
python train_reinforce.py --task_id sharded-livecodebench/2866
python train_reinforce.py --task_id sharded-livecodebench/2754
python train_reinforce.py --task_id sharded-livecodebench/2882
python train_reinforce.py --task_id sharded-livecodebench/2755
python train_reinforce.py --task_id sharded-livecodebench/2785
python train_reinforce.py --task_id sharded-livecodebench/2856
python train_reinforce.py --task_id sharded-livecodebench/2786
python train_reinforce.py --task_id sharded-HumanEval/139
python train_reinforce.py --task_id sharded-HumanEval/158
python train_reinforce.py --task_id sharded-livecodebench/2779
python train_reinforce.py --task_id sharded-HumanEval/159
python train_reinforce.py --task_id sharded-livecodebench/2857
python train_reinforce.py --task_id sharded-livecodebench/2955
python train_reinforce.py --task_id sharded-HumanEval/5
python train_reinforce.py --task_id sharded-livecodebench/2892
python train_reinforce.py --task_id sharded-HumanEval/113
python train_reinforce.py --task_id sharded-HumanEval/141
python train_reinforce.py --task_id sharded-HumanEval/76
python train_reinforce.py --task_id sharded-HumanEval/137
python train_reinforce.py --task_id sharded-HumanEval/26
python train_reinforce.py --task_id sharded-livecodebench/2728